/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int function_2() {
	volatile uint32_t variable_1 = 123;
	volatile uint32_t variable_2 = 456;

	if (variable_1 > variable_2) {
		variable_1 += 1;
		variable_2 *= 100;
	}


	return variable_1;
}

int function_1() {
	volatile uint32_t variable_A = 123;
	volatile uint32_t variable_B = 456;

	if (variable_A < variable_B) {
		function_2();
	}


	return variable_A;
}


uint32_t function_struct(uint32_t variable) {
	volatile uint32_t variable_2 = 1;
	volatile uint32_t variable_3 = 2;
	volatile uint32_t variable_4 = 3;

	variable_3 *= 100;
	variable_4 = variable_2 + variable_3;

	return variable + variable_2 + variable_3 + variable_4;
}


uint32_t function(uint32_t variable) {
	return variable + 1;
}


int main(void)
{
	volatile uint32_t x = 0;

	for (uint8_t i = 0; i < 5; i++) {
		x = function_struct(x);
	}

    /* Loop forever */
	for(;;);
}


/*
 *
	uint32_t return_value = 0;
	return_value = function_1();

 */
